Explicit return type for DecoratedModule.add()
When building with Typescript 1.6.2, without the explicit return type, the declaration in the generated .d.ts is "add(...providers: any[]): this:" which causes Typescript to give the following error when compiling against them:

ng-forward/cjs/classes/module.d.ts(6,31): Error TS1110: Type expected.